-- begin ATULSAMPLE_ORDER
alter table ATULSAMPLE_ORDER add constraint FK_ATULSAMPLE_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references ATULSAMPLE_CUSTOMER(ID)^
create index IDX_ATULSAMPLE_ORDER_CUSTOMER on ATULSAMPLE_ORDER (CUSTOMER_ID)^
-- end ATULSAMPLE_ORDER
